# Generated by Django 3.0.6 on 2020-05-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DecimalField(decimal_places=3, max_digits=5)),
                ('bitrate', models.PositiveIntegerField()),
                ('shape', models.CharField(choices=[('SIN', 'Sine'), ('SQU', 'Square'), ('TRI', 'Triangle')], default='SIN', max_length=3)),
            ],
            options={
                'ordering': ['frequency', 'shape', 'bitrate'],
            },
        ),
    ]
